### ISSUE TITLE
Spacing of items in toolbar

### ISSUE THREAD

**Issue by xiaosongshu** [ruddfawcett/RFKeyboardToolbar#14]
Is it possible to hardcode the position of the items in the toolbar?

I'm thinking of something like this:

`Dynamic_string_button............................................Bold...Italic...
`
The Dynamic_string_button is used as a sort of pseudo autocorrect based on a prepopulated list of words (appears based on what the user types). Bold and Italic button are used to modify the textView.

If the Dynamic_string_button doesn't match any keywords, then only Bold/Italic is shown, but they are still aligned to the right, so something like:

`.....................................................Bold....Italic`

**Comment by Hackmodford** [comment]
I believe this and #11 could be solved by using something like a flexible width space object. How to implement that is another story...

**Comment by ruddfawcett** [comment]
I agree with @Hackmodford — sounds like a flexible width space object, but because the toolbar isn't actually a UIToolbar (but rather a UIView with UIScrollView) you'd have to calculate the width of the buttons and then change the x-position of each, which is not scalable and rather tedious.

I'll think a bit more on this...
